modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="lemon_core"
    mandatory=true
    versionRange="[1.20.1-1.0.35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="scalar_utils"
    mandatory=true
    versionRange="[1.20.1-5.4.20,)"
    ordering="NONE"
    side="BOTH"